# SPDX-FileCopyrightText: 2025 Shun Sakai
#
# SPDX-License-Identifier: CC0-1.0

name: CI

on:
  pull_request:
  push:
    branches:
      - "master"

jobs:
  prettier:
    name: Prettier
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Setup Node.js environment
        uses: actions/setup-node@v5
        with:
          node-version: 22
      - name: Run formatter in check mode
        run: npx prettier -c "**.{md,yaml,yml}"
